### ISSUE TITLE
Simulation on Trieste bsub system

### ISSUE THREAD

**Issue by franzlongo** [thomasgas/ctools_pipe#6]
When submitting to the TS batch farm even the small background runs go to an infinite loop not closing the run.

**Comment by thomasgas** [comment]
The background simulation work for me. I updated the `jobs_bsub.sh` file to use a faster queue.
Remember to do a `git pull` inside the ctools_pipe folder. 
A quick reminder of the steps:

- source anaconda: `source /gpfs/glast/Users/tgaspar/software/anaconda3.sh` 
- activate the ctools environment: `source activate ctools_p3`
- `cd` into the `ctools_pipe` folder
- source   `variables_TS.sh`
- do the analysis

If the processes stops, try to re-run it with the same parameters.
Let me know if I can close the issue.

**Comment by thomasgas** [comment]
it works ;)
